export const COMMON_INDICATORS = {
  GDP: 'NY.GDP.MKTP.CD',
  GDP_PER_CAPITA: 'NY.GDP.PCAP.CD',
  POPULATION: 'SP.POP.TOTL',
  LIFE_EXPECTANCY: 'SP.DYN.LE00.IN',
  LITERACY_RATE: 'SE.ADT.LITR.ZS',
  CO2_EMISSIONS: 'EN.ATM.CO2E.KT',
  UNEMPLOYMENT: 'SL.UEM.TOTL.ZS',
  INFLATION: 'FP.CPI.TOTL.ZG',
  POVERTY_RATE: 'SI.POV.NAHC',
  INTERNET_USERS: 'IT.NET.USER.ZS',
  GNI_PER_CAPITA: 'NY.GNP.PCAP.CD',
} as const

export const QUICK_STAT_INDICATORS = [
  COMMON_INDICATORS.POPULATION,
  COMMON_INDICATORS.GDP,
  COMMON_INDICATORS.GNI_PER_CAPITA,
] as const
